---
- name: Ensure nginx, docker, pip are installed
  package:
    name:
      - nginx
      - docker.io
      - python3-pip
    state: present

- name: Ensure py-docker is installed
  pip:
    name: docker

- name: Ensure nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Add nginx configuration for youtubedl-server
  template:
    src: nginx_youtubedl.conf.j2
    dest: /etc/nginx/conf.d/youtubedl-server.conf
  notify: nginx_reload

- name: Clone repository
  git:
    repo: '{{ youtubedl_git_repo }}'
    dest: '{{ youtubedl_container_build_dir }}'
    version: '{{ youtubedl_git_branch }}'
  when: youtubedl_build_from_repo

- name: Build youtube-dl-server image
  docker_image:
    name: '{{ youtubedl_dockerhub_image }}'
    source: build
    build:
      path: '{{ youtubedl_container_build_dir }}'
      pull: true
      args:
        YOUTUBE_DL: '{{ youtubedl_build_youtubedl }}'
        ATOMICPARSLEY: '{{ youtubedl_build_atomicparsley | int }}'
    force_source: true
  when: youtubedl_build_from_repo

- name: Remove repository
  file:
    path: '{{ youtubedl_container_build_dir }}'
    state: absent
  when: youtubedl_build_from_repo

- name: Create host configuration directory
  file:
    path: '{{ youtubedl_config_host_location | dirname }}'
    state: directory
  when: youtubedl_config_host_location is defined

- name: Push youtube-dl configuration
  copy:
    src: '{{ youtubedl_configfile }}'
    dest: '{{ youtubedl_config_host_location }}'
    mode: 644
  when: youtubedl_config_host_location is defined
  register: config_pushed

- name: Create container volume list
  set_fact:
    volumes:
      - '{{ youtubedl_host_data_dir }}:/youtube-dl'

- name: Add config volume if set
  set_fact:
    volumes:
      - '{{ youtubedl_host_data_dir }}:/youtube-dl'
      - '{{ youtubedl_config_host_location }}:/usr/src/app/config.yml:ro'
  when: youtubedl_config_host_location is defined

- name: Launch youtube-dl-server container
  docker_container:
    name: youtube-dl-server
    pull: '{{ not youtubedl_build_from_repo }}'
    image: '{{ youtubedl_dockerhub_image }}'
    memory: '{{ youtubedl_memory_limit }}'
    restart_policy: unless-stopped
    user: '{{ youtubedl_user_uid }}:{{ youtubedl_user_gid }}'
    ports:
      - '127.0.0.1:{{ youtubedl_docker_port }}:8080'
    volumes: '{{ volumes }}'
    state: started
    restart: '{{ config_pushed.changed }}'
    env:
      PYTHONPATH: /youtube-dl/.python
      YDL_PYTHONPATH: /youtube-dl/.python
      YDL_CONFIG_PATH: /usr/src/app/config.yml
